version: "3.9"

services:
  diabetes_api:
    build: .
    container_name: diabetes_prediction_api
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
